import { Cloud, Sparkles, type LucideIcon } from "lucide-react";
import {
  siAirtable,
  siAndroid,
  siClaude,
  siCloudflare,
  siDocker,
  siElementor,
  siExpo,
  siFastapi,
  siFirebase,
  siFlutter,
  siGithubactions,
  siGoogleanalytics,
  siGooglesearchconsole,
  siGooglesheets,
  siGrafana,
  siGraphql,
  siHubspot,
  siHuggingface,
  siIos,
  siKotlin,
  siKubernetes,
  siLangchain,
  siLetsencrypt,
  siLighthouse,
  siMake,
  siN8n,
  siNestjs,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siPhp,
  siPostgresql,
  siPrisma,
  siPython,
  siReact,
  siRedis,
  siSentry,
  siShopify,
  siStripe,
  siSupabase,
  siSwift,
  siTailwindcss,
  siTerraform,
  siTypescript,
  siVercel,
  siWoocommerce,
  siWordpress,
  siZapier,
} from "simple-icons";

// A tech logo is either an SVG path (24x24 viewBox, from simple-icons) or a fallback lucide icon.
export type Tech = { name: string } & ({ path: string } | { icon: LucideIcon });

export const techStack = {
  airtable: { name: "Airtable", path: siAirtable.path },
  android: { name: "Android", path: siAndroid.path },
  aws: { name: "AWS", icon: Cloud },
  claude: { name: "Claude", path: siClaude.path },
  cloudflare: { name: "Cloudflare", path: siCloudflare.path },
  docker: { name: "Docker", path: siDocker.path },
  elementor: { name: "Elementor", path: siElementor.path },
  expo: { name: "Expo", path: siExpo.path },
  fastapi: { name: "FastAPI", path: siFastapi.path },
  firebase: { name: "Firebase", path: siFirebase.path },
  flutter: { name: "Flutter", path: siFlutter.path },
  githubActions: { name: "GitHub Actions", path: siGithubactions.path },
  googleAnalytics: { name: "Google Analytics", path: siGoogleanalytics.path },
  googleSheets: { name: "Google Sheets", path: siGooglesheets.path },
  grafana: { name: "Grafana", path: siGrafana.path },
  graphql: { name: "GraphQL", path: siGraphql.path },
  hubspot: { name: "HubSpot", path: siHubspot.path },
  huggingface: { name: "Hugging Face", path: siHuggingface.path },
  ios: { name: "iOS", path: siIos.path },
  kotlin: { name: "Kotlin", path: siKotlin.path },
  kubernetes: { name: "Kubernetes", path: siKubernetes.path },
  langchain: { name: "LangChain", path: siLangchain.path },
  letsencrypt: { name: "Let's Encrypt", path: siLetsencrypt.path },
  lighthouse: { name: "Lighthouse", path: siLighthouse.path },
  make: { name: "Make", path: siMake.path },
  n8n: { name: "n8n", path: siN8n.path },
  nestjs: { name: "NestJS", path: siNestjs.path },
  nextjs: { name: "Next.js", path: siNextdotjs.path },
  nginx: { name: "NGINX", path: siNginx.path },
  nodejs: { name: "Node.js", path: siNodedotjs.path },
  openai: { name: "OpenAI", icon: Sparkles },
  php: { name: "PHP", path: siPhp.path },
  postgresql: { name: "PostgreSQL", path: siPostgresql.path },
  prisma: { name: "Prisma", path: siPrisma.path },
  python: { name: "Python", path: siPython.path },
  react: { name: "React", path: siReact.path },
  reactNative: { name: "React Native", path: siReact.path },
  redis: { name: "Redis", path: siRedis.path },
  searchConsole: { name: "Search Console", path: siGooglesearchconsole.path },
  sentry: { name: "Sentry", path: siSentry.path },
  shopify: { name: "Shopify", path: siShopify.path },
  stripe: { name: "Stripe", path: siStripe.path },
  supabase: { name: "Supabase", path: siSupabase.path },
  swift: { name: "Swift", path: siSwift.path },
  tailwindcss: { name: "Tailwind CSS", path: siTailwindcss.path },
  terraform: { name: "Terraform", path: siTerraform.path },
  typescript: { name: "TypeScript", path: siTypescript.path },
  vercel: { name: "Vercel", path: siVercel.path },
  woocommerce: { name: "WooCommerce", path: siWoocommerce.path },
  wordpress: { name: "WordPress", path: siWordpress.path },
  zapier: { name: "Zapier", path: siZapier.path },
} satisfies Record<string, Tech>;

export type TechId = keyof typeof techStack;

export const trustStrip: TechId[] = [
  "react",
  "nextjs",
  "nodejs",
  "python",
  "aws",
  "claude",
  "openai",
  "flutter",
  "wordpress",
];
